### ISSUE TITLE
userscript does not execute when its `@name` begins with a numeric character

### ISSUE THREAD

**Issue by warren-bank** [wbayer/webview-gm#5]
for example:

```text
// ==UserScript==
// @name         123 ABC
// @description  Error: name cannot begin with a numeric character
// @namespace    WebViewWM
// @match        *://*
// @run-at       document-start
// ==/UserScript==

window.alert("document-start" + "\n" + window.location.href)
```

- - - -

unrelated to this issue..
* I really appreciate this library.. it works (nearly) perfect
  - I stumbled across it while searching (unsuccessfully) for the source of the old/beta version of [TamperMonkey for Android](https://play.google.com/store/apps/details?id=net.biniok.tampermonkey)
  - this is better.. for my needs
* I just pushed a [repo](https://github.com/warren-bank/Android-WebMonkey) that has a slightly modified version of your demo app
  - it adds some additional javascript API methods that I wanted to be able to call from my userscripts
  - non-standard extention to the standard GM API
  - will probably add more over time..

- - - -

cross-reference to [the same issue](https://github.com/warren-bank/Android-WebMonkey/issues/1) in my repo

**Comment by warren-bank** [comment]
Having only taken a quick scan through the code to determine the cause for this observed behavior, I would make the following (untested) guess:

the problem originates in the javascript that is injected by the WebView client.. specifically:
* [this line](https://github.com/wbayer/webview-gm/blob/v1.2.0/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/run/WebViewClientGm.java#L123) declares a String prefix in Java:
  ```java
    String callbackPrefix = (script.getName() + script.getNamespace() + UUID.randomUUID().toString()).replaceAll("[^0-9a-zA-Z_]", "");
  ```
* [`GM_xmlhttpRequest`](https://github.com/wbayer/webview-gm/blob/v1.2.0/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/run/WebViewClientGm.java#L157) declares a function in javascript
  - it's long so I won't copy it verbatim
  - the important parts are where it uses the `callbackPrefix` String<br>for example:
    ```javascript
      "unsafeWindow." + callbackPrefix + "GM_onAbortCallback = details.onabort;"
    ```

so..
* when `name` is: "123ABC"
* in Java, `callbackPrefix` is a String: "123ABCXYZ"
* in javascript, `window.123ABCXYZGM_onAbortCallback = ()=>{}`
  - Error: `Uncaught SyntaxError: Invalid or unexpected token`

my suggestion:
* on [this line](https://github.com/wbayer/webview-gm/blob/v1.2.0/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/run/WebViewClientGm.java#L123), update the dynamic prefix to always begin with a static non-numeric substring (ex: __"cb_"__):
  ```java
    String callbackPrefix = ("cb_" + script.getName() + script.getNamespace() + UUID.randomUUID().toString()).replaceAll("[^0-9a-zA-Z_]", "");
  ```

**Comment by warren-bank** [comment]
The above guess has been [confirmed](https://github.com/warren-bank/Android-WebMonkey/commit/acd430612911e71fd99a9ac5dd59b3a6c40aae2b) to fix this issue.

**Comment by wbayer** [comment]
Hi Warren,
thank you for your interest in the library and for your research regarding this bug! Would you please create a pull request to fix it here as well?

**Comment by warren-bank** [comment]
Thank you for writing and sharing this library; it suits my needs perfectly. I'll gladly send you a PR (shortly).
