### ISSUE TITLE
regex pattern doesn't match URLs when used in @include, @exclude, or @match

### ISSUE THREAD

**Issue by warren-bank** [wbayer/webview-gm#8]
this is because of a minor bug [here](https://github.com/wbayer/webview-gm/blob/fad9c2b5958cdc581e2738e2812695e53ae1e18d/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/util/CriterionMatcher.java#L43):
* the value of the parameter passed to `isRegExp()` is `url`, rather than `criterion`

**Comment by warren-bank** [comment]
fixed by PR #9

**Comment by wbayer** [comment]
Thank you for finding and fixing this bug, @warren-bank
